on:
  push:
    branches:
      - uat  # Ce workflow s'exécute uniquement pour la branche uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages (UAT)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Dossier source, racine du dépôt
          destination_dir: uat  # Déploie les fichiers dans le dossier /uat dans gh-pages
